### ISSUE TITLE
Extract Hyperparameters to Splunk Fields

### ISSUE THREAD

**Issue by rmbryan71** [garysieling/deeplens-experiments#12]

**Comment by rmbryan71** [comment]
Why is the sourcetype on these events "http" when the event collector is set to json?
https://prd-p-vtk8vp5x5ggv.cloud.splunk.com/en-US/manager/search/http-eventcollector

**Comment by garysieling** [comment]
When I switched to elastic search, I broke these out into a hyperparameters object
