### ISSUE TITLE
Does k-means give the same accuracy, if you run it several times in a row? -- Data Request

### ISSUE THREAD

**Issue by rmbryan71** [garysieling/deeplens-experiments#26]
Gary - I have the data from this experiment, but I don't have a way to tell one run from another, except by guessing on label and duration fields.
Is there a way I could get a unique incrementing number per "run" or, I guess, even the run start time would be enough?

**Comment by garysieling** [comment]
Yeah, probably, though for this ticket I was thinking to just extract the variance

**Comment by rmbryan71** [comment]
There is no variance in precision, f1-score or recall within a species for multiple runs using kmeans.
This table shows there is only one value for each metric per species across 8 runs: http://165.227.103.185:5601/app/kibana#/visualize/edit/de1a88d0-680b-11e8-aa7a-89fb74d43a0e?_g=()&_a=(filters:!(),linked:!t,query:(language:lucene,query:''),uiState:(vis:(params:(sort:(columnIndex:3,direction:desc)))),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(field:label.keyword,size:100),schema:bucket,type:significant_terms),(enabled:!t,id:'9',params:(field:f1-score),schema:metric,type:cardinality),(enabled:!t,id:'10',params:(field:precision),schema:metric,type:cardinality),(enabled:!t,id:'11',params:(field:recall),schema:metric,type:cardinality)),params:(perPage:100,showMeticsAtAllLevels:!f,showPartialRows:!f,showTotal:!f,sort:(columnIndex:3,direction:desc),totalFunc:sum),title:'k-means+accuracy+variance',type:table))

**Comment by garysieling** [comment]
Oh, interesting. Is there a way to put error bars on the charts?

https://www.elastic.co/guide/en/elasticsearch/guide/current/_building_bar_charts.html

**Comment by garysieling** [comment]
There is a random seed that I might need to change to be actually random too

**Comment by garysieling** [comment]
Added a runid
